timelessco/recollect

- src/utils/commonData.tsx
> fix(count): 🐛 fixed types section count

- cypress.config.ts
- cypress/support/commands.ts
- package.json
- src/pageComponents/login/index.tsx
> fix(cypress): 🐛 cypress setup fix

- src/pages/_app.tsx
added analytics and meta tags
[1]:
[2]:
> feat(tracking): ✨ added analytics and meta tags

- src/pageComponents/dashboard/cardSection/listBox.tsx
- src/pageComponents/dashboard/index.tsx
added uncategorised option in bottom bar
[1]:
[2]:
> feat(bottom bar): ✨ added uncategorized option

- src/pages/api/file/upload-file.ts
> fix(api size): 🐛 updated upload api size limit

- src/pageComponents/dashboard/index.tsx
- src/pages/api/file/upload-file.ts
> fix(payloay issue): 🚧 removed thumbnail logic to test payload issue

- src/pageComponents/dashboard/index.tsx
> fix(thumbnail): 🚧 added back the thumbnail logic

- project-words.txt
- src/async/mutationHooks/files/useFileUploadOptimisticMutation.ts
- src/async/supabaseCrudHelpers.ts
- src/pages/api/file/upload-file.ts
- src/types/apiTypes.ts
- src/types/componentTypes.ts
> fix(upload): 🚧 poc fix for upload 4.5mb limit issue

- src/pages/_app.tsx
> fix(analytics): 📈 only have the analytics script when in production

- package.json
- pnpm-lock.yaml
- src/components/modal.tsx
- src/pageComponents/dashboard/modals/videoModal.tsx
- src/utils/helpers.ts
> fix(video): 🐛 added aspect ratio to video modal

- src/pageComponents/dashboard/dashboardLayout.tsx
> style(search): 💄 centered search bar

- env.local.txt
- env/schema.js
- src/pages/[category_id]/[id].tsx
- src/pages/_app.tsx
- src/pages/api/bookmark/add-bookmark-min-data.ts
- src/pages/api/share/send-collaboration-email.ts
- src/utils/constants.ts
> fix(urls server): 🐛 fixed all server urls

- src/async/supabaseCrudHelpers.ts
> fix: 🐛 fixed clear trash url issue

- src/pageComponents/settings/deleteAccount.tsx
- src/utils/helpers.ts
> fix(del user): 🐛 fixed del user redirect issue

- src/pageComponents/dashboard/index.tsx
- src/utils/constants.ts
> fix(minor bugs): 🐛 fixed url regz and file name parser

- src/pageComponents/dashboard/cardSection/index.tsx
> fix(img size): 🐛 increased cover img default size

- src/styles/globals.css
> fix(settings): 🐛 mobile settings modal z-index

- env/schema.js
- project-words.txt
- src/pages/_app.tsx
> fix(fix): ⚡️ minor fixes

- src/async/mutationHooks/files/useFileUploadOptimisticMutation.ts
- src/async/supabaseCrudHelpers.ts
- src/pageComponents/dashboard/index.tsx
- src/pages/api/file/upload-file.ts
- src/types/apiTypes.ts
> fix(upload): 🐛 file duplicate issue

- src/pageComponents/dashboard/index.tsx
- src/pages/api/bookmark/clear-bookmark-trash.ts
- src/pages/api/bookmark/delete-bookmark.ts
- src/types/apiTypes.ts
> fix(delete files): 🐛 file delete s3 sync

- README.md
- src/components/ariaDisclosure/index.tsx
- src/components/ariaDropdown/ariaDropdown.tsx
- src/icons/downArrowGray.tsx
- src/pageComponents/dashboard/sidePane/collectionsList.tsx
- src/pageComponents/dashboard/sidePane/sidePaneTypesList.tsx
- src/styles/globals.css
> feat(collections): ✨ added collapse in side pane

- src/pages/api/file/upload-file-remaining-data.tsx
- src/pages/api/file/upload-file.ts
- src/utils/constants.ts
> fix(uplad): 🐛 added new remaining upload api

- src/pages/api/file/upload-file-remaining-data.tsx
> fix(upload): 🐛 added description in remaining api

- src/icons/actionIcons/audioIcon.tsx
- src/pageComponents/dashboard/cardSection/index.tsx
> fix(audio icon): 💄 fixed size

- src/pageComponents/settings/deleteAccount.tsx
- src/pages/[category_id].tsx
- src/pages/index.tsx
> fix(ssr): 🐛 removed getserversideprops

- src/pageComponents/dashboard/dashboardLayout.tsx
> fix(icon): 🐛 view condition fix

- src/pageComponents/dashboard/dashboardLayout.tsx
> fix(header): 🐛 drag handle header z index

- .github/DEVELOPMENT.md
- .github/SELF_HOST.md
- README.md
> docs(self host): 📝 added slef hosting docs

- .github/DEVELOPMENT.md
- src/pages/api/share/update-shared-category-user-role.ts
> fix(share api): 🐛 share api query condition and minor docs fix

- src/pageComponents/dashboard/dashboardLayout.tsx
> fix(side pane): 🐛 added flicker fix

- package.json
- src/pages/api/bookmark/add-bookmark-min-data.ts
- src/pages/api/file/upload-file.ts
> fix(upload file): 🐛 added upload api collection api check

- src/pages/api/file/upload-file-remaining-data.tsx
- src/pages/api/file/upload-file.ts
> fix(video): 🐛 added video blur hash fix

- src/pages/api/v1/ai/search/get.ts
> fix(ai search): ✨ added score filter

- vercel.json
> fix: 🐛 increased timeout for api

- src/pages/api/bookmark/add-bookmark-min-data.ts
…lementation
revert the broken links approach
> refactor(handler): 🛠️ comment out URL validation logic for future implementation

- src/pageComponents/dashboard/index.tsx
- src/pageComponents/dashboard/modals/settingsModal.tsx
- Now pasting in input fields or modals does not add bookmark
- added proper comments to ensure readablity
> fix(global-paste): fixed the global paste issue

- src/utils/constants.ts
… kinda links
Changed regex to allow .engineering and .design type of links as well (not only .com)
> feat(regex-link): 🐛 made the regex to accept .engineering and .design kind of links

- src/pages/api/bookmark/add-bookmark-min-data.ts
- src/pages/api/bookmark/add-url-screenshot.ts
> fix(metadata): 🐛 fixed meta data generation for bookmarks

- src/pageComponents/dashboard/cardSection/previewLightBox.tsx
Removed unnecessary console.log() statement
> fix(preview-lightbox): remove debug logs for state transitions

- src/pages/api/bookmark/add-bookmark-min-data.ts
> fix(min data): 🚑️ added userid and email check

- src/async/queryHooks/bookmarks/useFetchBookmarkById.ts
- src/pageComponents/dashboard/cardSection/listBox.tsx
- src/pageComponents/dashboard/cardSection/option.tsx
- src/pageComponents/dashboard/cardSection/previewLightBox.tsx
- src/utils/constants.ts
> fix(preview-lightbox): correct lazy loading behavior

- src/async/mutationHooks/bookmarks/useAddBookmarkMinDataOptimisticMutation.ts
- src/pageComponents/dashboard/cardSection/index.tsx
- src/pages/api/bookmark/add-bookmark-min-data.ts
- src/pages/api/bookmark/add-remaining-bookmark-data.ts
- src/pages/api/bookmark/add-url-screenshot.ts
- src/pages/api/file/upload-file-remaining-data.tsx
- src/pages/api/file/upload-file.ts
- src/pages/api/v1/tests/file/post/upload.ts
- src/types/apiTypes.ts
> All bookmarks should have screenshot, and meta data generation related to that

- src/async/mutationHooks/bookmarks/useAddBookmarkMinDataOptimisticMutation.ts
- src/components/LightBox.tsx
- src/pageComponents/dashboard/cardSection/index.tsx
- src/pageComponents/dashboard/cardSection/previewLightBox.tsx
- src/pages/[category_id]/preview/[id].tsx
- src/pages/api/bookmark/add-bookmark-min-data.ts
- src/pages/api/bookmark/add-remaining-bookmark-data.ts
- src/pages/api/bookmark/add-url-screenshot.ts
- src/pages/api/file/upload-file-remaining-data.tsx
- src/pages/api/file/upload-file.ts
- src/pages/api/v1/tests/file/post/upload.ts
- src/types/apiTypes.ts
> refactor(preview-lightbox): cleaned up the code of the lightbox

- src/async/supabaseCrudHelpers/index.ts
- src/async/uploads/file-upload.ts
- src/components/ariaMultiSelect/index.tsx
- src/pages/api/file/upload-file.ts
- src/pages/api/v1/tests/file/post/upload.ts
- src/types/apiTypes.ts
> perf(thumbnail): ✨ updated logic to generate thumbnail in client side

- src/async/mutationHooks/bookmarks/useAddBookmarkScreenshotMutation.ts
- src/pageComponents/dashboard/cardSection/index.tsx
- src/utils/getBlurHash.ts
> WIP fix(refresh-screenshot): refresh screenshot once it comes

- src/components/LightBox.tsx
- src/pageComponents/dashboard/cardSection/index.tsx
- src/pageComponents/dashboard/cardSection/objectFallBack.tsx
- src/pageComponents/dashboard/cardSection/previewLightBox.tsx
- src/pages/[category_id]/preview/[id].tsx
> fix(sidebar-issues): fix the issues in sidebar

- src/pageComponents/dashboard/cardSection/objectFallBack.tsx
> fix(2x-images): fix 2X images

- src/pageComponents/dashboard/cardSection/objectFallBack.tsx
2x screenshots gets displayed correctly
> fix(2x-screenshot): 2x screenshot needs to work properly

- src/pages/api/v1/bucket/get/signed-url.tsx
> feat(api): ✨ added API for r2 signed URL generation

- src/components/LightBox.tsx
…m animation
ligtbox can now be zoomed and scrollable
> feat(lightbox): enhance slide rendering with image dimensions and zom

- src/pages/api/bookmark/add-bookmark-min-data.ts
- src/pages/api/bookmark/add-remaining-bookmark-data.ts
made some changes in the favIconLogic function we get the googles fallback if the website don't have any favicon, since we have our own logic we hit that link if the response is not 200, we return null to render own fallback
> fix(favIcon): if it is a google's fallback we return null

- src/pages/api/file/get-pdf-buffer.ts
- src/utils/apiHelpers.ts
moved the array buffer fetch to the api to avoid the cors error
> fix: refacor the fetch the buffer of pdf

- src/utils/apiHelpers.ts
> fix: throw errors

- src/components/lightbox/LightBox.tsx
https://github.com/user-attachments/assets/8c0978bd-6b87-4233-9094-69e8c9ac9b49
zoom now works for all images
> feat(image-zoom): ✨ now zoom works for ever image

- src/async/queryHooks/bookmarks/useSearchBookmarks.ts
- src/components/searchInput.tsx
- src/pageComponents/dashboard/cardSection/index.tsx
- searchbar does not autofocus 
- no results found does not flash
- search indicator is a subtle icon instead of text
https://github.com/user-attachments/assets/7a51da42-99c3-4348-94a6-705397805a22
> fix(loader): revamp search loader 

- src/components/lightbox/LightBox.tsx
- src/components/lightbox/LightBoxPlugin.tsx
- src/components/lightbox/previewLightBox.tsx
- src/pageComponents/dashboard/cardSection/index.tsx
- src/types/apiTypes.ts
- src/utils/helpers.ts
- we conditionally fetch bookmarks based on search text 
https://github.com/user-attachments/assets/a0318a58-bf2e-44ee-bf76-08388345a837
> feat(search-lightbox): ✨ now lightbox works in searched bookmarks as  expected

- next.config.js
> fix(img optimisation): ✨ updated the prod condition

- src/components/ariaMultiSelect/index.tsx
- src/components/checkbox.tsx
- src/pageComponents/dashboard/index.tsx
- now if there is a tag which is aleredy there we dont show it in create 
- fixed checkbox bug
https://github.com/user-attachments/assets/f601b367-2c32-4c50-9b82-9665aef733a5
fixed css bug of wrapper not adapting to content height
> feat(tags): fix dupicate tags and handle the dropdown properly

- src/pages/api/bookmark/add-remaining-bookmark-data.ts
- src/pages/api/share/send-email.ts
- src/utils/constants.ts
1. add zod validation to the send-email api 
2. add image/jpeg into constants and update,add-remaining-bookmark-data.ts accordingly
> refactor: ♻️ add zod validation

- src/components/ariaMultiSelect/index.tsx
- src/components/lightbox/LightBox.tsx
- src/pageComponents/dashboard/cardSection/option.tsx
- src/pageComponents/dashboard/index.tsx
- src/pageComponents/dashboard/share/shareContent.tsx
- src/pageComponents/dashboard/sidePane/singleListItemComponent.tsx
- updated iframe styles, only mounts when we go to that slide, added white bg
- updated styles for tags, changed size added proper space between each tag
- disabling lightbox in public page
- fixed collection dropdown in hard links
- added public page indicator in sidebar
> fix(public-page-click): fix public page click in lightbox

- src/pageComponents/dashboard/cardSection/imageCard.tsx
- src/pageComponents/dashboard/cardSection/index.tsx
- removed loader from list view 
- optimised code
> fix(remove-text-loader): 🐛 remove loader from list view

- src/pages/api/v1/twitter/sync.ts
- src/pages/api/v1/twitter/syncFolders.ts
create new api for creating new collection for the folders we fetch from the twitter, we create the collection with the icon 'boookmark'
even if the collection already exist we create another one with the same name 
if the bookmark belongs to a collection, while fetching the bookmark we iterate it and look for collection name if it exist we look of the url in the main table and update the category_id accordingly
> feat(sync-twitter-folders): separate api to create collection for twitter folders

- src/components/lightbox/LightBoxPlugin.tsx
- src/pages/api/v1/twitter/sync.ts
- src/pages/api/v1/twitter/syncFoldersBookmarks.ts
1. in meta_data we use image_caption instead of img_caption for twitter, so changed accordingly to display the image caption
1. removed the 'add the bookmark to the collection': update the category id in main table and moved to syncFoldersBookmarks api
1. added the 'add the bookmark to the collection' logic here : it is moved from Sync API to reduce complexity
> feat(syncFoldersBookmarks): add new endpoint for updating category

- src/pages/api/bookmark/fetch-bookmarks-data.ts
- src/pages/api/v1/twitter/sync.ts
_Main reason for changing :_ **when we import the twitter data the newest first uploaded to the db and oldest is uploaded on top of it, so if we fetch the bookmarks the oldest comes first and latest goes to the bottom** 
for twitter the **inserted_at** is the time the tweet is created
> feat(bookmarks): add ordering to bookmarks retrieval by insertion date
